TesteBackendV2/Models/equipment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TesteBackendV2.Models
{
    public class equipment
    {
        [Key]
        public Guid id { get; set; }
        public Guid equipment_model_id { get; set; }
        [Display(Name = "Nome do Equipamento")]
        public string name { get; set; }   
    }
}

TesteBackendV2/Controllers/equipment_position_historyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteBackendV2.Data;
using TesteBackendV2.Models;

namespace TesteBackendV2.Controllers
{
    public class equipment_position_historyController : Controller
    {
        private readonly TesteBackendV2Context _context;

        public equipment_position_historyController(TesteBackendV2Context context)
        {
            _context = context;
        }

        // GET: equipment_position_history
        public async Task<IActionResult> Index(Guid? equipment_id)
        {
            return View(await _context.equipment_position_history
                .Where(x => x.equipment_id == equipment_id)
                .OrderByDescending(x => x.date)
                .ToListAsync());
        }

        // POST: equipment_position_history/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("equipment_id,date,lat,lon")] equipment_position_history equipment_position_history)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipment_position_history);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment_position_history);
        }
    }
}

TesteBackendV2/Controllers/equipment_state_historyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteBackendV2.Data;
using TesteBackendV2.Models;

namespace TesteBackendV2.Controllers
{
    public class equipment_state_historyController : Controller
    {
        private readonly TesteBackendV2Context _context;

        public equipment_state_historyController(TesteBackendV2Context context)
        {
            _context = context;
        }

        // GET: equipment_state_history
        public async Task<IActionResult> Index(Guid? equipment_id)
        {
            return View(await _context.equipment_state_history
                .Where(x => x.equipment_id == equipment_id)
                .OrderByDescending(x => x.date)
                .ToListAsync());
        }

        // POST: equipment_state_history/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("equipment_id,date,equipment_state_id")] equipment_state_history equipment_state_history)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipment_state_history);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment_state_history);
        }
    }
}

TesteBackendV2/Controllers/equipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteBackendV2.Data;
using TesteBackendV2.Models;

namespace TesteBackendV2.Controllers
{
    public class equipmentsController : Controller
    {
        private readonly TesteBackendV2Context _context;

        public equipmentsController(TesteBackendV2Context context)
        {
            _context = context;
        }

        // GET: equipments
        public async Task<IActionResult> Index()
        {
            return View(await _context.equipment.ToListAsync());
        }

        // GET: equipments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: equipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,equipment_model_id,name")] equipment equipment)
        {
            if (ModelState.IsValid)
            {
                equipment.id = Guid.NewGuid();
                _context.Add(equipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: equipments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.equipment.FindAsync(id);
            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        // POST: equipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,equipment_model_id,name")] equipment equipment)
        {
            if (id != equipment.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!equipmentExists(equipment.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: equipments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.equipment
                .FirstOrDefaultAsync(m => m.id == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var equipment = await _context.equipment.FindAsync(id);
            _context.equipment.Remove(equipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool equipmentExists(Guid id)
        {
            return _context.equipment.Any(e => e.id == id);
        }
    }
}

TesteBackendV2/Views/equipments/Create.cshtml
@model TesteBackendV2.Models.equipment

@{
    ViewData["Title"] = "Create";
}

<h4>Equipamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="equipment_model_id" class="control-label"></label>
                <input asp-for="equipment_model_id" class="form-control" />
                <span asp-validation-for="equipment_model_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteBackendV2/Views/equipments/Delete.cshtml
@model TesteBackendV2.Models.equipment

@{
    ViewData["Title"] = "Delete";
}

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>Equipamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.equipment_model_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.equipment_model_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

TesteBackendV2/Views/equipments/Edit.cshtml
@model TesteBackendV2.Models.equipment

@{
    ViewData["Title"] = "Edit";
}

<h4>Equipamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="equipment_model_id" class="control-label"></label>
                <input asp-for="equipment_model_id" class="form-control" />
                <span asp-validation-for="equipment_model_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteBackendV2/Views/equipments/Index.cshtml
@model IEnumerable<TesteBackendV2.Models.equipment>

@{
    ViewData["Title"] = "Index";
}

<h1>Equipamentos</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.equipment_model_id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.equipment_model_id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-controller="equipment_state_history" asp-action="Index" asp-route-equipment_id="@item.id">Estados</a> |
                <a asp-controller="equipment_position_history" asp-action="Index" asp-route-equipment_id="@item.id">Posições</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>