TesteBackendV2/Models/equipment_model.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TesteBackendV2.Models
{
    public class equipment_model
    {
        [Key]
        public Guid id { get; set; }
        [Display(Name = "Nome do Modelo")]
        public string name { get; set; }
    }
}

TesteBackendV2/Controllers/equipment_modelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteBackendV2.Data;
using TesteBackendV2.Models;

namespace TesteBackendV2.Controllers
{
    public class equipment_modelController : Controller
    {
        private readonly TesteBackendV2Context _context;

        public equipment_modelController(TesteBackendV2Context context)
        {
            _context = context;
        }

        // GET: equipment_model
        public async Task<IActionResult> Index()
        {
            return View(await _context.equipment_model.ToListAsync());
        }

        // GET: equipment_model/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: equipment_model/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name")] equipment_model equipment_model)
        {
            if (ModelState.IsValid)
            {
                equipment_model.id = Guid.NewGuid();
                _context.Add(equipment_model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment_model);
        }

        // GET: equipment_model/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment_model = await _context.equipment_model.FindAsync(id);
            if (equipment_model == null)
            {
                return NotFound();
            }
            return View(equipment_model);
        }

        // POST: equipment_model/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,name")] equipment_model equipment_model)
        {
            if (id != equipment_model.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipment_model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!equipment_modelExists(equipment_model.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipment_model);
        }

        // GET: equipment_model/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment_model = await _context.equipment_model
                .FirstOrDefaultAsync(m => m.id == id);
            if (equipment_model == null)
            {
                return NotFound();
            }

            return View(equipment_model);
        }

        // POST: equipment_model/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var equipment_model = await _context.equipment_model.FindAsync(id);
            _context.equipment_model.Remove(equipment_model);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool equipment_modelExists(Guid id)
        {
            return _context.equipment_model.Any(e => e.id == id);
        }
    }
}

TesteBackendV2/Controllers/equipment_model_state_hourly_earningsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteBackendV2.Data;
using TesteBackendV2.Models;

namespace TesteBackendV2.Controllers
{
    public class equipment_model_state_hourly_earningsController : Controller
    {
        private readonly TesteBackendV2Context _context;

        public equipment_model_state_hourly_earningsController(TesteBackendV2Context context)
        {
            _context = context;
        }

        // GET: equipment_model_state_hourly_earnings
        public async Task<IActionResult> Index(Guid? equipment_model_id)
        {
            return View(await _context.equipment_model_state_hourly_earnings
                .Where(x => x.equipment_model_id == equipment_model_id)
                .ToListAsync());
        }

        // POST: equipment_model_state_hourly_earnings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("equipment_model_id,equipment_state_id,value")] equipment_model_state_hourly_earnings equipment_model_state_hourly_earnings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipment_model_state_hourly_earnings);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment_model_state_hourly_earnings);
        }
    }
}

TesteBackendV2/Views/equipment_model/Create.cshtml
@model TesteBackendV2.Models.equipment_model

@{
    ViewData["Title"] = "Create";
}

<h4>Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteBackendV2/Views/equipment_model/Delete.cshtml
@model TesteBackendV2.Models.equipment_model

@{
    ViewData["Title"] = "Delete";
}

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>Modelo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

TesteBackendV2/Views/equipment_model/Edit.cshtml
@model TesteBackendV2.Models.equipment_model

@{
    ViewData["Title"] = "Edit";
}

<h4>Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteBackendV2/Views/equipment_model/Index.cshtml
@model IEnumerable<TesteBackendV2.Models.equipment_model>

@{
    ViewData["Title"] = "Index";
}

<h1>Modelos</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-controller="equipment_model_state_hourly_earnings" asp-action="Index" asp-route-equipment_model_id="@item.id">Valor Hora</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>